# 5.9 ジョブ間のデータ共有

name: Share job data

on: push

jobs:
  before:
    runs-on: ubuntu-latest
    steps:
      - id: generate
        run: echo "result=Hello" >> "$GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.generate.outputs.result }} # ジョブレベルの出力値
  after:
    runs-on: ubuntu-lsatest
    needs: [before]
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }}
        run: echo "${RESULT}"
